---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    local:
      hosts:
        localhost:
          ansible_host:
          ansible_ssh_private_key_file:
          ansible_connection: local


...
